# Appveyor configuration template for Rust using rustup for Rust installation
# https://github.com/starkat99/appveyor-rust

os: Visual Studio 2015

environment:
  channel: stable
  target: i686-pc-windows-msvc
  nodejs_version: "8"

install:
  - ps: Install-Product node $env:nodejs_version
  - cd tools\legal
  - npm install
  - cd ..\..
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv --default-toolchain %channel% --default-host %target%
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - rustc -vV
  - cargo -vV

build_script:
  - node tools\legal Cargo.lock
  - cargo-build --release --verbose %cargoflags%

after_build:
  - 7z a inno_updater.zip %APPVEYOR_BUILD_FOLDER%\target\i686-pc-windows-msvc\release\inno_updater.exe %APPVEYOR_BUILD_FOLDER%\Cargo.lock

test: off

artifacts:
  - path: inno_updater.zip
    name: Inno Updater

deploy:
  release: $(APPVEYOR_REPO_TAG_NAME)
  description: 'Inno Updater'
  provider: GitHub
  auth_token:
    secure: 2nTTfcrtyfyNmPghlEfIfz/z4OxaetWnofUKHnwp8/kUt6/D6KcpK3LfTx6CxFmo
  artifact: inno_updater.zip
  draft: false
  prerelease: false
  on:
    branch: master
    appveyor_repo_tag: true
